name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: lang.github.io
      uses: 742093571/lang.github.io@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: 742093571/lang.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm && npm build
        BUILD_DIR: docs/.vuepress/dist/